export const imageList = [
    { img: 'components/art/assets/Africa-Hotel.jpg' },
    { img: 'components/art/assets/Architectural-Digest.jpeg' },
    { img: 'components/art/assets/Ball in the field.jpg' },
    { img: 'components/art/assets/Brdige-by-the-ocean2.jpg' },
    { img: 'components/art/assets/Bridge by the Ocean.jpg' },
    { img: 'components/art/assets/defense-watch-tower..jpg' },
    { img: 'components/art/assets/Detailed-floor.jpeg' },
    { img: 'components/art/assets/Detailed-mall-wall.jpg' },
    { img: 'components/art/assets/DownTop-Ceiling.jpg' },
    { img: 'components/art/assets/Fake-restaurant-plants.jpeg' },
    { img: 'components/art/assets/Imani-Collective.jpeg' },
    { img: 'components/art/assets/Mall-Wall.jpg' },
    { img: 'components/art/assets/Moon Light.jpg' },
    { img: 'components/art/assets/Pattern-floor.jpeg' },
    { img: 'components/art/assets/Patterned-school-walkway.jpeg' },
    { img: 'components/art/assets/Seedling.jpeg' },
    { img: 'components/art/assets/Petrol Station.jpg' },
    { img: 'components/art/assets/Red-brick-wall.jpeg' },
    { img: 'components/art/assets/Restaurant.jpg' },
    { img: 'components/art/assets/Detailed-Tree-bark.jpeg' },
    { img: 'components/art/assets/Vintage-Sgr-Metal.jpeg' },
];
