export const categorizedCertificates = {
  "Technical Certifications": [
    { name: "Lyft - Back-End Engineering Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/Lyft/xSw9echtixLAoPdsH_Lyft_cmq5Hpw99mdHAm5wy_1703688690191_completion_certificate.pdf" },
    { name: "Create Your First Web App with Python and Flask", url: "https://www.coursera.org/account/accomplishments/records/XBN2HEQEZPWH" },
    { name: "Building Smart Business Assistants with IBM Watson", url: "https://www.coursera.org/account/accomplishments/records/M55RS9U53LUC" },
    { name: "Command Line in Linux", url: "https://www.coursera.org/account/accomplishments/records/KASEAH2AY6EE" },
    { name: "Create Your First Python Program From UST", url: "https://www.coursera.org/account/accomplishments/records/KY6PBWZAF4P9" },
    { name: "Getting Started with Kaggle", url: "https://www.coursera.org/account/accomplishments/records/EGKKHYMSJL2W" },
    { name: "Introduction to Bash Shell Scripting", url: "https://www.coursera.org/account/accomplishments/records/MHW3G9HQYRQY" },
    { name: "IBM Learning: Introduction to Open Source", url: "#" },
    { name: "J.P. Morgan - Software Engineering Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/J.P.%20Morgan/R5iK7HMxJGBgaSbvk_J.P.%20Morgan_cmq5Hpw99mdHAm5wy_1695224034892_completion_certificate.pdf" },
    { name: "J.P.Morgan Chase & Co. - Software Engineering Lite Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/J.P.%20Morgan/Wb4yEmHvZrC2qxiyX_JPMorgan%20Chase%20&%20Co._cmq5Hpw99mdHAm5wy_1696340758177_completion_certificate.pdf" },
    { name: "Start the UX Design Process: Empathize, Define, and Ideate", url: "https://www.coursera.org/account/accomplishments/records/Z3WZ2JZLMHWG" },
    { name: "Foundations of User Experience (UX) Design", url: "https://www.coursera.org/account/accomplishments/records/7JGZWDNDVX6N" },
    { name: "Machine Learning for All", url: "https://www.coursera.org/account/accomplishments/records/CPGQDQJ2G3C9" },
    { name: "Programming for Everybody (Getting Started with Python)", url: "https://www.coursera.org/account/accomplishments/records/ZA9K2G52AZSN" },
    { name: "Introduction to CSS3", url: "https://www.coursera.org/account/accomplishments/records/BYG8JWMG6DJY" },
    { name: "Introduction to HTML5", url: "https://www.coursera.org/account/accomplishments/records/TGXEY74SK2GW" },
  ],
  "Finance & Trading Simulations": [
    { name: "Quant Accelerator Simulation Experience", url: "#" },
    { name: "CME Group: Introduction to Crude Oil", url: "#" },
    { name: "CME Group: Introduction to Precious Metals", url: "#" },
    { name: "CME Group: Introduction to Grains and Oilseeds", url: "#" },
    { name: "CME Group: Micro FX Futures", url: "#" },
    { name: "CME Group: Intro To FX", url: "#" },
    { name: "AmplifyMe Finance Accelerator Simulation Experience in Partnership with Morgan Stanley", url: "https://my.amplifyme.com/certificate/76b17038-9711-4d4a-9c9b-e4ed73a5bfcd/" },
    { name: "J.P.Morgan Chase & Co. - Agile Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/J.P.%20Morgan/5QiaMtZ4k8ngYKn4D_JPMorgan%20Chase%20&%20Co._cmq5Hpw99mdHAm5wy_1696353311675_completion_certificate.pdf" },
  ],
  "Professional Development": [
    { name: "McKinsey Forward Program", url: "https://www.credly.com/badges/f8d52c6e-8f93-4520-8529-587da7592fb3/public_url" },
    { name: "JPMorgan Chase & Co. - Agile Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/J.P.%20Morgan/5QiaMtZ4k8ngYKn4D_JPMorgan%20Chase%20&%20Co._cmq5Hpw99mdHAm5wy_1696353311675_completion_certificate.pdf" },
    { name: "Introduction to Agile: Scrum and Kanban", url: "https://ude.my/UC-10dfcafd-f83e-4ac7-b2fe-ea383bf6028b" },
    { name: "JPMorgan Chase & Co. - Corporate Analyst Development Program (CADP) Job Simulation", url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/JP%20Morgan%20Chase%20Corporate/4dy5SP43KMPppKz2i_JPMorgan%20Chase%20&%20Co._cmq5Hpw99mdHAm5wy_1672139191083_completion_certificate.pdf" },
  ],
};
